# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1411825003);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1411824475);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1411824883);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1411824763);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.provider.0.gethashURL", "http://localhost/safebrowsing-dummy/gethash");
user_pref("browser.safebrowsing.provider.0.updateURL", "http://localhost/safebrowsing-dummy/update");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140924083558");
user_pref("browser.slowStartup.averageTime", 1092);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.buildID", "20140924083558");
user_pref("browser.startup.homepage_override.mstone", "32.0.3");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"webrtc-status-button\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"social-share-button\",\"action-button--jid1-brkhfpgs4eiedqjetpack-mozilla-link\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"action-button--jid1-brkhfpgs4eiedqjetpack-mozilla-link\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"newElementCount\":0}");
user_pref("browser.warnOnQuit", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1411910343304");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1411823943304");
user_pref("datareporting.sessions.current.activeTicks", 5);
user_pref("datareporting.sessions.current.firstPaint", 1009);
user_pref("datareporting.sessions.current.main", 41);
user_pref("datareporting.sessions.current.sessionRestored", 1128);
user_pref("datareporting.sessions.current.startTime", "1411825799911");
user_pref("datareporting.sessions.current.totalTime", 27);
user_pref("datareporting.sessions.currentIndex", 10);
user_pref("datareporting.sessions.previous.0", "{\"s\":1411823942908,\"a\":1,\"t\":31,\"c\":true,\"m\":31,\"fp\":2939,\"sr\":3878}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1411823984524,\"a\":2,\"t\":8,\"c\":true,\"m\":31,\"fp\":1799,\"sr\":1926}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1411824311687,\"a\":2,\"t\":8,\"c\":true,\"m\":30,\"fp\":960,\"sr\":1082}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1411824354067,\"a\":8,\"t\":139,\"c\":true,\"m\":40,\"fp\":1496,\"sr\":1629}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1411824496987,\"a\":3,\"t\":20,\"c\":true,\"m\":31,\"fp\":934,\"sr\":1067}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1411824519317,\"a\":2,\"t\":10,\"c\":true,\"m\":30,\"fp\":943,\"sr\":1078}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1411824546203,\"a\":2,\"t\":11,\"c\":true,\"m\":41,\"fp\":963,\"sr\":1100}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1411824567204,\"a\":2,\"t\":17,\"c\":true,\"m\":31,\"fp\":943,\"sr\":1079}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1411824613859,\"a\":2,\"t\":6,\"c\":true,\"m\":30,\"fp\":952,\"sr\":1109}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1411824642462,\"a\":21,\"t\":396,\"c\":true,\"m\":31,\"fp\":999,\"sr\":1123}");
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.errorconsole.enabled", true);
user_pref("devtools.selfxss.count", 10);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_TOOLBOX_OPENED_PER_USER_FLAG\":\"32.0.3\",\"DEVTOOLS_WEBCONSOLE_OPENED_PER_USER_FLAG\":\"32.0.3\"}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.autoDisableScopes", 10);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.blocklist.url", "http://localhost/extensions-dummy/blocklistURL");
user_pref("extensions.bootstrappedAddons", "{\"jid1-BrKhfPGs4EiEDQ@jetpack\":{\"version\":\"0.1\",\"type\":\"extension\",\"descriptor\":\"/home/will/venvs/powerbase-plugin/pbaseplugin/ffx-sdk/t5ixddie.default/extensions/jid1-BrKhfPGs4EiEDQ@jetpack.xpi\"},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"32.0.3\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"32.0.3\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.checkCompatibility.32.0", false);
user_pref("extensions.checkCompatibility.nightly", false);
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:32.0.3");
user_pref("extensions.enabledScopes", 5);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1411550988000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1411633467000,\"rdfTime\":1411549861000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1411550987000}}},{\"name\":\"app-profile\",\"addons\":{\"jid1-BrKhfPGs4EiEDQ@jetpack\":{\"descriptor\":\"/home/will/venvs/powerbase-plugin/pbaseplugin/ffx-sdk/t5ixddie.default/extensions/jid1-BrKhfPGs4EiEDQ@jetpack.xpi\",\"mtime\":1411825799000}}}]");
user_pref("extensions.installDistroAddons", false);
user_pref("extensions.lastAppVersion", "32.0.3");
user_pref("extensions.lastPlatformVersion", "32.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.sdk.console.logLevel", "info");
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.update.url", "http://localhost/extensions-dummy/updateURL");
user_pref("extensions.webservice.discoverURL", "http://localhost/extensions-dummy/discoveryURL");
user_pref("gecko.buildID", "20140924083558");
user_pref("gecko.mstone", "32.0.3");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 92695);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("toolkit.startup.last_success", 1411825799);
user_pref("toolkit.telemetry.previousBuildID", "20140924083558");
user_pref("urlclassifier.updateinterval", 172800);
